//v170 Copyright (c) 2008-2020 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
(function(){var e=window,l=document,g={distro:"AFSH",id:"AFSH-"+(new Date).getTime()};Tynt.AFSHL=!0;Date.now||(Date.now=function(){return(new Date).getTime()});var f={_maxRef:600,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",init:function(){this._icUrl=g.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=g.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=g.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=g.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js"},
newEle:function(a,b,c,d){d=d||window;a=d.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,b,c){b=b||window;a=this.newEle("script",{async:"async",referrerPolicy:"unsafe-url",type:"text/javascript",src:a},null,b);this.insertEle(a,c||b.document.getElementsByTagName("script")[0])},injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var d=
{width:a.width+"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(d,c);c=this.newEle("iframe",{referrerPolicy:"unsafe-url",src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},d);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+
this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=b);return b},_imgs:[],injectPixel:function(a,b,c){var d;try{d=l.createElement("img")}catch(k){d=document.createElement("img")}d&&(this._imgs.push(d),b&&(d.onload=b),c&&(d.onerror=c),d.referrerPolicy="unsafe-url",d.src=a)},docUrl:function(){var a=this.getLink("canonical");
a||(a=this.getMeta("property","og:url","name","original-source"));if(a){if(0!=a.indexOf("http")){var b=g.protocol+e.location.host+e.location.pathname,c=l.getElementsByTagName("base")[0];c&&(c=c.getAttribute("href"))&&(b=c);"/"==a.charAt(0)?(c=b.indexOf("/",9),-1<c&&(b=b.slice(0,c))):(c=b.lastIndexOf("/"),b=9<c?b.slice(0,c+1):b+"/");a=b+a}return a}return""},getMeta:function(a,b,c,d){var k,e=null,f=null,h=l.getElementsByTagName("meta");for(k=0;k<h.length;++k)e||h[k].getAttribute(a)!==b?c&&!f&&h[k].getAttribute(c)===
d&&(f=h[k].getAttribute("content")||null):e=h[k].getAttribute("content")||null;return e||f},getLink:function(a,b){var c,d,e=l.getElementsByTagName("link");for(c=0;c<e.length;++c)if(d=e[c].getAttribute("rel"),e[c].getAttribute("href")&&d&&(!b&&0<=d.indexOf(a)||b&&d==a))return e[c].href;return null},extend:function(a,b){var c,d;for(c=1;c<arguments.length;++c)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&(a[d]=arguments[c][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===
Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},d=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,d.push(a[b]));return d},iframeType:function(){var a=this.iframeEle(),b=v;if(a)b=a.id&&0<=a.id.search(/google_ads?_i?frame/)?6:w;else try{window!=window.top&&(b=
"undefined"!=typeof window.$sf?x:t)}catch(c){b=t,f.clog("iframeType: "+c.message)}return b},iframeEle:function(a){var b=null;a=a||window;try{b=a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},isolated:function(){var a=!0;try{"function"==typeof window.top.open&&(a=!1)}catch(b){}return a},
tyntIds:function(){return this.unique(Tynt).join("~")},getPubId:function(){for(var a=null,b=0;b<Tynt.length;++b)if("string"==typeof Tynt[b]&&22==Tynt[b].length&&0>Tynt[b].indexOf("!")){a=Tynt[b];break}return a},countIds:function(a){var b,c=0;for(b=0;b<Tynt.length;++b)Tynt[b]===a&&++c;return c},_log:function(a){"undefined"==typeof Tynt.debug&&0<e.location.search.indexOf("__tcdebugmode=1")&&e.console&&e.console.log&&(Tynt.debug=!0);if(!0===Tynt.debug||1===Tynt.debug)a.unshift("[TC]"),e.console.log.apply(e.console,
a)},log:function(){g.inXOIframe()?this.clog.apply(this,arguments):this._log(this.toArray(arguments))},clog:function(){var a=this.toArray(arguments);a.unshift(g.id);this._log(a)},callIcU:function(){e._33Across.state.icDone=y;f.clog("Calling IC/U");this.injectPixel(this._icUrl+"/u",function(){e._33Across.state.icDone=r})},callIc:function(){var a,b,c,d,k,m,p,h;if(!e._33Across.state.icDone){e._33Across.state.icDone=y;b=this.getCookie(l.cookie,"tracertraffic");a=e.location.hash;a=/tynt=/.test(a)?a.match(/tynt=?([^?&$#]*)/)[1]:
!1;d=c=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+g.type+"&ts="+Date.now()+"&dn="+g.distro+"&iso="+(this.isolated()?"1":"0")+(null==n.uspString?"":"&us_privacy="+n.uspString);(a=this.getMeta("property","og:image:url","property","og:image"))&&(d+="&img="+encodeURIComponent(this.trunc(a,250)));k=d;(a=this.getMeta("property","og:title"))&&a!=l.title&&(k+="&ct="+encodeURIComponent(this.trunc(a,200)));m=k;l.referrer&&(a=this.trunc(l.referrer,
this._maxRef),m+="&r="+encodeURIComponent(a));p=m;if(a=l.title||e.location.hostname)a=this.trim(this.trunc(a,200)),p+="&t="+encodeURIComponent(a);h=p;if(a=this.docUrl())a=this.trunc(a,400),h+="&cu="+encodeURIComponent(a);b=h;if(a=this.getLink("amphtml",!0))a=this.trunc(a,250),b+="&ah="+encodeURIComponent(a);f.callIc.rsp=function(){e._33Across.state.icDone=r};f.clog("Calling IC");this.injectPixel(b,f.callIc.rsp,function(){f.injectPixel(h,f.callIc.rsp,function(){f.injectPixel(p,f.callIc.rsp,function(){f.injectPixel(m,
f.callIc.rsp,function(){f.injectPixel(k,f.callIc.rsp,function(){f.injectPixel(d,f.callIc.rsp,function(){f.injectPixel(c,f.callIc.rsp)})})})})})})}},callDeb:function(a,b,c){function d(a,b){f.clog("Calling DEB "+b+(a?"":" on IC timeout"));var c=encodeURIComponent(f.trunc(l.referrer,f._maxRef)),d=n.uspString&&4==n.uspString.length?"&us_privacy="+n.uspString:"";f.injectScript(f._debUrl+"?id="+f.tyntIds()+"&dn="+g.distro+"&cc="+b+"&r="+c+d,e)}"undefined"==typeof a&&(a=1);e._33Across.state.deDone>=a||(++e._33Across.state.deDone,
1!==e._33Across.state.deDone&&!0!==c||this.when(function(){return e._33Across.state.icDone==r},d,{timeout:300,timeoutCallback:d,callbackData:e._33Across.state.deDone},this),b&&0<b.length&&setTimeout(function(){f.callDeb(a,b,!0)},b.shift()))},callDebX:function(a,b){function c(a,c){f[b?"log":"clog"]("Calling DEBx "+c+(a?"":" on IC timeout"));var m=encodeURIComponent(f.trunc(l.referrer,f._maxRef)),p=u.consentString?"&gdpr_consent="+u.consentString:"",h=n.uspString&&4==n.uspString.length?"&us_privacy="+
n.uspString:"";f.injectScript(f._debUrl+"?m=xch&id="+f.tyntIds()+"&dn="+g.distro+"&cc="+c+"&r="+m+p+h,e)}a||(a=10);e._33Across.state.dxDone>=a||(++e._33Across.state.dxDone,this.when(function(){return e._33Across.state.icDone==r},c,{timeout:300,timeoutCallback:c,callbackData:e._33Across.state.dxDone},this))},jsonDecode:function(a){if("function"!=typeof Array.prototype.toJSON)return JSON.stringify(a);var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=
b;return a},getCookie:function(a,b){for(var c=b+"=",d=a.split(";"),e=0;e<d.length;e++){for(var f=d[e];" "==f.charAt(0);)f=f.substring(1,f.length);if(0==f.indexOf(c))return f.substring(c.length,f.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,d;if(!a||a.length<=b)return a;c=a.substring(0,b);for(d=1;3>=d;++d)if("%"==c.charAt(c.length-d))return c.substring(0,c.length-d);return c},when:function(a,b,c,d){var f,m,g,h=null,z=null,q=a();c=c||{};f=c.interval||
50;m=c.timeout;g=c.timeoutCallback||function(){};if(q)return b.call(d,q,c.callbackData),!0;h=e.setInterval(function(){if(q=a())e.clearInterval(h),e.clearTimeout(z),b.call(d,q,c.callbackData)},f);m&&(z=e.setTimeout(function(){e.clearInterval(h);g.call(d,q,c.callbackData)},m));return!1},prob:function(a){a=parseFloat(a)||0;return Math.random()<a},on:function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,d||!1):a.attachEvent&&a.attachEvent("on"+b,c)},off:function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,
c,d||!1):a.detachEvent&&a.detachEvent("on"+b,c)}},u={consentString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__cmpLocator&&(b=a)}catch(c){}if(a===window.top)break;a=a.parent}var d={};e.__cmp=function(a,c,e){if(b){var f=Math.random()+"";a={__cmpCall:{command:a,parameter:c,callId:f}};d[f]=e;b.postMessage(a,"*")}else e({msg:"CMP not found"},!1)};f.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=JSON.parse(a.data)}catch(c){}b.__cmpReturn&&
(a=b.__cmpReturn,d[a.callId](a.returnValue,a.success),delete d[a.callId])},!1)},c=function(){e.__cmp("getConsentData",null,function(b,c){c&&(a.consentString=b.consentData)})};e.__cmp||b();try{c()}catch(d){b(),c()}Tynt.getConsentString=function(){return a.consentString}}},n={uspString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__uspapiLocator&&(b=a)}catch(c){}if(a===window.top)break;a=a.parent}var d={};e.__uspapi=function(a,c,e){if(b){var f="usp-"+Math.random();
a={__uspapiCall:{command:a,callId:f,version:c}};d[f]=e;b.postMessage(a,"*")}else e({msg:"__uspapi not found"},!1)};f.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=JSON.parse(a.data)}catch(c){}b.__uspapiReturn&&(a=b.__uspapiReturn,d[a.callId](a.returnValue,a.success),delete d[a.callId])},!1)},c=function(){e.__uspapi("getUSPData",1,function(b,c){c&&(a.uspString=b.uspString)})};e.__uspapi||b();try{c()}catch(d){b(),c()}Tynt.getUspString=function(){return a.uspString}}},
y=1,r=2,v=0,t=3,x=4,w=5;g.type=0;g.inIframe=function(){return this.type>v};g.inSOIframe=function(){return this.type>=w&&6>=this.type};g.inXOIframe=function(){return this.type>=t&&this.type<=x};g.init=function(){this.type=f.iframeType();this.inSOIframe()&&(e=f.getTopWin(),l=e.document);e._33Across||(e._33Across={});e._33Across.state||(e._33Across.state={icDone:0,deDone:0,dxDone:0,ivDone:!1});this.protocol="https://";f.init();u.init();n.init();this.isolated=f.isolated();f.clog("xoi="+this.inXOIframe()+
", soi="+this.inSOIframe()+", iso="+this.isolated);e._33Across.pvTs||(e._33Across.pvTs=Date.now())};g.init();g.inXOIframe()?f.clog("cross-origin iframes are not supported"):(f.callIc(),f.callDeb(1))})();
